name: dotnet-codecoverage
description: Publish .Net Solutuon Code Coverage

inputs: 
    dotnetVersion:
        description: version of the dotnet libary example 6.0.x
        required: true
    
runs:
    using: "composite"
    steps:

        - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: ${{ inputs.dotnetVersion}}
        
        - name: Restore dependencies
        run: dotnet restore
        
        - name: Build
        run: dotnet build --no-restore
        
        - name: Test
        run: dotnet test --no-build --verbosity normal
        
        - name: Generate coverage report
        run: |
            cd ./MyLibrary.Tests/
            dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
        
        - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: ./MyLibrary.Tests/TestResults/coverage.info 