name: build-stage-dotnet
description: Stage for Building and Testing a .Net Solution.

inputs: 
    dotnetVersion:
        description: usage of the paramter
        required: true
    dotnetProjectName:
        description: Name of the .Net Projects where Coverage test will be run.
        required: true
    solutionDirectory:
        description: Directory location of the .Net Solution file.
        required: true

runs:
  using: "composite"
  steps:
  - uses: ./.github/templates/steps/dotnet-build
    with:
      dotnetVersion: ${{ inputs.dotnetVersion}}
      solutionDirectory: ${{ inputs.solutionDirectory}}

  - uses: ./.github/templates/steps/dotnet-codecovrage
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/Main' }}
    with:
      dotnetProjectName: ${{ inputs.dotnetProjectName}}
      solutionDirectory: ${{ inputs.solutionDirectory}}
