name: dotnet
description: Restore, Build & Test a .Net Solutuon

inputs: 
    dotnetVersion:
        description: version of the dotnet libary example 6.0.x
        required: true
    solutionDirectory:
        description: Directory location of the .Net Solution file.
        required: true
    
run:
    using: "composite"
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnetVersion }}
    
    - name: Restore dependencies
      run: |
        cd ${{inputs.solutionDirectory}}
        dotnet restore
    
    - name: Build Solution
      run: |
        cd ${{inputs.solutionDirectory}}
        run: dotnet build --no-restore
    
    - name: Test Solution
      run: |
        cd ${{inputs.solutionDirectory}}
        run: dotnet test --no-build --verbosity normal