name: CICD Library - SleeDigital LabelStore Library (Nuget)

on:
  push:
    branches: 
    - 'Main'
    - 'feature/**'
  pull_request:
    branches: 
    - 'Main'
    
env:
  libraryType: nuget # Options: nuget, npm
  dotnetLibraryName: SleeDigital.LabelStore.Library # Name of the libary Solution File name and directory name (.Net/Nuget), they need to be the same.
  npmLibraryName: n/a # TBD
  rootDirectory: ./src/SharedLibraries
  developmentFrameworkVersion: 6.0.x # if .Net example 6.0.x / 

jobs:
  build:
    name: build-stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build-dotnet
        uses: ./.github/templates/stages/build-stage-dotnet
        if: ${{ env.libraryType == 'nuget' }}
        with:
          dotnetVersion: ${{ env.developmentFrameworkVersion}}
          dotnetProjectName: ${{ env.dotnetLibraryName }}
          solutionDirectory: ${{ env.rootDirectory }}/${{ env.libraryType }}/${{ env.dotnetLibraryName }}
