name: CICD Library - SleeDigital LabelStore Library (Nuget)

on:
  push:
    branches: 
    - 'Main'
    - 'feature/**'
  pull_request:
    branches: 
    - 'Main'
    
env:
  dotnetSolutionName: SleeDigital.LabelStore.Library # Name of the libary Solution File name and directory name (.Net/Nuget), they need to be the same.
  rootDirectory: ./src/SharedLibraries/nuget
  developmentFrameworkVersion: 6.0.x # if .Net example 6.0.x / 

jobs:
  build:
    name: build-stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: dotnetbuild
        uses: ./.github/templates/steps/dotnet-build
        with:
            dotnetVersion: ${{ env.developmentFrameworkVersion}}
            solutionDirectory: ${{ env.rootDirectory }}/${{ env.libraryType }}/${{ env.dotnetLibraryName }}

      - name: dotnet-codecoverage
        uses: ./.github/templates/steps/dotnet-codecoverage
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/Main' }}
        with:
            dotnetProjectName: ${{ env.dotnetSolutionName}}
            solutionDirectory: ${{ env.rootDirectory }}/${{ env.dotnetLibraryName }}